version: '3'
services:
  main_api:
    build: './main_api'
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    depends_on:
      - main_api
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
